platform:ios, 7.0
target "pieceSample" do 
pod 'UIActivityIndicator-for-SDWebImage'
pod 'AFNetworking', '2.6.3'
pod 'Reachability'
pod 'UIColor+MLPFlatColors'
pod 'SVProgressHUD', '~> 1.0'
pod 'HCYoutubeParser'
pod 'Google/Analytics', '~> 1.0.0'
pod 'PayPal-iOS-SDK'
end

